language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  include:
    - rust: nightly
      os: linux
      script:
        - cargo build --features nightly --release
        - cargo test --features nightly --verbose
      env:
        - DEPLOY=true
    - rust: nightly
      os: osx
      script:
        - cargo build --features nightly --release
        - cargo test --features nightly --verbose
      env:
        - DEPLOY=true
    - rust: nightly
      os: linux
      script:
        - cargo build --features "nightly clippy"
