[package]
authors = ["yamakaky"]
name = "dcpu"
version = "0.1.2"
description = "An assembler, debugger and emulator for the DCPU-16"
homepage = "https://github.com/Yamakaky/dcpu"
repository = "https://github.com/Yamakaky/dcpu"
documentation = "https://docs.rs/dcpu"
license = "LGPL-3.0"
readme = "README.md"

[dependencies]
byteorder = "~0.5.1"
docopt = "~0.6.80"
enum_primitive = "~0.1.0"
log = "~0.3.6"
nom = "~1.2.2"
num = "~0.1.31"
rustc-serialize = "~0.3.19"
simplelog = "~0.2.0"
glium = "0.15"

[profile.release]
lto = true
